Module2 task2
htmlacademy-adaptive/1703957-cat-energy-22 pull request #6
Opened 2021-03-29 10:21 UTC by slyvka-tanya

2021-03-29 19:31 UTC, Pakistanka requested changes

2021-03-29 19:31 UTC, Pakistanka commented on source/form.html
> +            <li class="main-nav__item"><a>Подбор прогараммы</a></li>
Опечатка - https://prnt.sc/10z9568

2021-03-29 19:31 UTC, Pakistanka commented on source/form.html
> +            <li class="main-nav__item"><a>Каталог продукции</a></li>
Потеряны  в ссылках href атрибуты, должно быть
`<a href="#"></a>`

2021-03-29 19:31 UTC, Pakistanka commented on source/form.html
> +                <p>
А зачем вокруг label и input?

Если хочешь обертку, то лучше использовать div

2021-03-29 19:31 UTC, Pakistanka commented on source/form.html
> +                <p>
Для оберток тег параграф мы не используем

2021-03-29 19:31 UTC, Pakistanka commented on source/form.html
> +                  <li>
Здесь li уместно

2021-03-29 19:48 UTC, slyvka-tanya commented on source/form.html
> +                  <li>
не поняла. Здесь все хорошо ?

2021-03-31 10:15 UTC, Pakistanka requested changes

2021-03-31 10:15 UTC, Pakistanka commented on source/form.html
> +            <li class="main-nav__item"><a>Подбор программы</a></li>
Потерян атрибут href

2021-03-31 15:08 UTC, ynsem commented on source/form.html
> +        <div class="social__icon__wrapper">
БЭМ

2021-03-31 16:06 UTC, slyvka-tanya commented on source/form.html
> +                  </button>
тогда добавлю через css

2021-03-31 19:20 UTC, slyvka-tanya commented on Readme.md
> +* Наставник: [Анастасия Полозова](https://htmlacademy.ru/profile/id258631).
done

2021-03-31 19:22 UTC, slyvka-tanya commented on source/form.html
> +        <img src="img/index/header-logo-mobile.svg" width="101" height="18" alt="Логотип текст">
хорошо, поняла.

2021-03-31 19:23 UTC, slyvka-tanya commented on source/form.html
> +        <h1 class="main__title">Подбор прогараммы</h1>
done

2021-03-31 19:23 UTC, slyvka-tanya commented on source/form.html
> +    <footer class="footer">
поняла

2021-03-31 19:25 UTC, slyvka-tanya commented on source/form.html
> +                  <input class="form__data-name" id="name" type="text" name="name" placeholder="БАРСИК">
сделала одним классом, потом через child размери зделаю

2021-03-31 19:26 UTC, slyvka-tanya commented on source/form.html
> +                    <span class="checkbox-image"></span>
так и думала, но сделала чтобы пусто не было

2021-03-31 19:30 UTC, ynsem commented on source/form.html
> +      <a class="header__logo" href="index.html">
название блока исправила, а элемента забыла, должно быть main-header__logo

2021-03-31 19:30 UTC, ynsem commented on source/form.html
> +        <div class="main-footer__address__wrapper address__wrapper">
смотри два нижних подчеркивания отделяют элемент, и у тебя получается main-footer - это блок, у него есть элемент main-footer__address, и тут же ты у него делаешь элемент __wrapper - это неправильно
если ты хотела написать элемент обертка адреса, то должно быть так:
`<div class="main-footer__address-wrapper address-wrapper">`
ну и дальше везде address__wrapper замени на address-wrapper

вот по этому месту понятно почему так?

2021-03-31 19:30 UTC, ynsem commented on source/form.html
> +        <div class="social__link__wrapper">
такая же история как и у адреса элемент элемента, так нельзя

2021-03-31 19:30 UTC, ynsem commented on source/index.html
> +            <li class="main-nav__item"><a> Каталог продукции</a>  </li>
не забывай у ссылок ставить href

2021-03-31 19:30 UTC, ynsem commented on source/index.html
> +          <div class="address__wrapper__text__wrapper">
элемент элемента элемента элемента, к сожалению так нельзя-нельзя-нельзя

2021-03-31 19:31 UTC, slyvka-tanya commented on source/index.html
> +          <div class="address__wrapper__text__wrapper">
с названиями классов у меня проблемы

2021-03-31 19:33 UTC, slyvka-tanya commented on source/form.html
> +      <a class="header__logo" href="index.html">
в этой версии провтикала

2021-03-31 19:34 UTC, slyvka-tanya commented on source/form.html
> +        <div class="main-footer__address__wrapper address__wrapper">
да, там и внизу будет такая же ошибка

2021-03-31 19:34 UTC, ynsem commented on source/img/form/icon_email.svg
> +</svg>
у тебя одни и те же иконки лежат в разных папках, так нельзя, количество загружаемых ресурсов необходимо минимизировать
складывай все в img, убирай отдельные папки

2021-03-31 19:38 UTC, slyvka-tanya commented on source/img/form/icon_email.svg
> +</svg>
поняла

2021-03-31 19:55 UTC, merged